GridLayout:

    
    cols: 2


    Label:
        id: moeda1
        text: 'Texto 1'
        font_size: 20 
        color: 1, 1, 1, 1
    Label: 
        id: moeda2
        text: 'Texto 2'
        font_size: 20
        color: 1, 1, 1, 1
    Label:
        id: moeda3
        text: 'Texto 3'
        font_size: 20
        color: 1, 1, 1, 1        
    Label: 
        id: moeda4
        text: 'Texto 4'
        font_size: 20
        color: 1, 1, 1, 1

